import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { nanoid } from 'nanoid'
import { Resend } from 'resend'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { email, companyName, role, auditData, totalMonthlySavings, totalAnnualSavings, teamSize, useCase } = body

    if (!email) {
      return NextResponse.json({ error: 'Email required' }, { status: 400 })
    }

    // Save lead
    const { error: leadError } = await supabase.from('leads').insert({
      email,
      company_name: companyName,
      role,
      team_size: teamSize,
      audit_data: auditData,
      total_savings: totalMonthlySavings,
    })

    if (leadError) throw leadError

    // Save shareable audit
    const slug = nanoid(10)
    const { error: auditError } = await supabase.from('audits').insert({
      slug,
      audit_data: auditData,
      total_monthly_savings: totalMonthlySavings,
      total_annual_savings: totalAnnualSavings,
      use_case: useCase,
      team_size: teamSize,
    })

    if (auditError) throw auditError

    const shareUrl = `${process.env.NEXT_PUBLIC_APP_URL}/audit/${slug}`
    const isHighSavings = totalMonthlySavings > 500

    // Send email
    await resend.emails.send({
      from: 'AI Spend Audit <onboarding@resend.dev>',
      to: email,
      subject: 'Your AI Spend Audit Report',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
          <h2 style="color: #059669;">Your AI Spend Audit is Ready</h2>
          <p>Hi${companyName ? ` from ${companyName}` : ''},</p>
          <p>Your audit is complete. Here's a summary:</p>
          <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 12px; padding: 20px; margin: 20px 0; text-align: center;">
            <p style="color: #059669; font-size: 14px; margin: 0 0 4px;">Total potential savings</p>
            <p style="font-size: 36px; font-weight: bold; color: #047857; margin: 0;">$${totalMonthlySavings}/mo</p>
            <p style="color: #6b7280; font-size: 14px; margin: 4px 0 0;">$${totalAnnualSavings} saved annually</p>
          </div>
          <p>View your full shareable report here:</p>
          <a href="${shareUrl}" style="display: inline-block; background: #059669; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 500;">View My Audit Report</a>
          ${isHighSavings ? `
          <div style="margin-top: 24px; background: #111827; color: white; border-radius: 12px; padding: 20px;">
            <p style="font-weight: 600; margin: 0 0 8px;">You could save even more with Credex</p>
            <p style="color: #9ca3af; font-size: 14px; margin: 0 0 16px;">Credex provides discounted AI credits — same tools, lower cost. Teams saving $500+/mo are our best fit.</p>
            <a href="https://credex.rocks" style="display: inline-block; background: #059669; color: white; padding: 10px 20px; border-radius: 8px; text-decoration: none; font-size: 14px;">Book a Credex consultation</a>
          </div>` : ''}
          <p style="color: #9ca3af; font-size: 12px; margin-top: 24px;">This audit was generated by AI Spend Audit, a free tool by Credex.</p>
        </div>
      `,
    })

    return NextResponse.json({ success: true, slug })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: 'Something went wrong' }, { status: 500 })
  }
}